### ISSUE TITLE
Cant ranked teams league points

### ISSUE THREAD

**Issue by blurfx** [encratite/LibOfLegends#19]
League (RANKED_TEAM_3x3): SILVER I, ? LP (Kassadin's Shadowdancers)
League (RANKED_TEAM_3x3): SILVER II, ? LP (Kassadin's Shadowdancers)
League (RANKED_SOLO_5x5): GOLD IV, 79 LP (Amumu's Runemasters)
League (RANKED_TEAM_5x5): SILVER III, ? LP (Galio's Outriders)

i tried other username for test, but ranked teams league point always return null.

its bug?

**Comment by encratite** [comment]
No, this is actually intended because team ratings work differently and require association with a team ID which I couldn't be bothered to look up ;[ I could work on it, but I'm not overly interested in it honestly. Talk to the people in the Riot Control channel if you want to fix this badly: http://riot.cont.ro.lt/#chat

**Comment by blurfx** [comment]
o, i see.

but i have a new qustion. liboflegends cant get ranked game loses anymore? it always return .

**Comment by encratite** [comment]
Riot removed that, nothing I can do about it
