### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ArkadianZ** [encratite/LibOfLegends#5]
I was wondering what the ETA would be on the LibOfLegends stand alone client, or if it would be possible to patch the current version. I think Riot changed where the values were read from in the last patch.

**Comment by encratite** [comment]
I'm already working on a stand-alone client in the master branch of RiotControl. The old centralised web service was "backup-forked" into the "centralised" branch but I doubt I'm ever going to work on that again. You probably need a NoSQL solution and a superior HTTP framework to make better use of the hardware. As for the ETA, I have no idea. Probably at least another 3-7 days, it remains to be seen. I just committed a patch for the example application that improves the visual output and conceals the bogus rating values.

You might actually still be able to determine your normal Elo in the same way you can tell your own ranked Elo when it's below 1200. You just need to play a game and log the Air traffic when you receive your end of game stats. I haven't checked it out, though. I don't even know what those packets look like for ranked games but this is definitely worth investigating.

If such a solution is found I am actually tempted to keep it private because Riot might just crack down on it again and then I'm running in the dark.

**Comment by ArkadianZ** [comment]
I'm going to make a forum request on GD in League forums to try coax an answer from a Rioter to see why exactly they are so temperamental about us viewing our stats.

**Comment by encratite** [comment]
Haha, good luck with that. I already talked to a Riot community representative yesterday and he said he wasn't at liberty to comment. The best we can hope for is getting publicity and outrage within the community, eventually causing them to provide proper statistics for all game modes...
